version: '3.5'

services:
  app-territorio-digital:
    image: wfelipe2011/app-territorio-digital:acp
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
    ports:
      - '13000-13100:5000' # Suponha que seu frontend esteja em execução na porta 80
    networks:
      - proxy

networks:
  proxy:
    external: true
