version: '3.5'

services:
  frontend:
    image: wfelipe2011/app-territorio-digital:acp
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
    ports:
      - '13000:3000' # Suponha que seu frontend esteja em execução na porta 80

